### ISSUE TITLE
Closing the command channel is closing all files

### ISSUE THREAD

**Issue by fachat** [fachat/XD2031#151]
Was detected with the "dsk2file" utility. It was closing the command channel, which closed the other channels as well incorrectly.

**Comment by greg-king5** [comment]
Actually, the DOS is supposed to do that.  The DOS's command "file" is supposed to be open permanently.  When the computer opens the command file, the DOS should see it as simply printing to its (already open) "file".  When the computer closes the command file, the DOS is supposed to close every _other_ file.  The purpose of closing the command file is to clean up, at the _end_ of a program; it makes sure that there are no unclosed (splat) files left behind.

So ...
The actual bugs are that the XD2031's command "file" was closed _too_; and, that the application (dsk2file) closes the file at the wrong time -- it should open the command file _before_ openning any other files on that device; and, close the command file _only after_ closing all other files on that device.

**Comment by fachat** [comment]
Hm. So. Why does dsk2file then actually work on a real drive?

**Comment by fachat** [comment]
Interesting. I just tried dsk2file on the VICE emulator, with xpet and two 2031 disk drives (as quick 1541 substitutes), two 1001 disk drives, and one 4040 disk drive. On all situations dsk2file breaks - until I move the close of the command channel to after the close of the file. Indeed @greg-king5  is right. I'll reopen this one until I've reverted the change.
(what makes me wonder where I did test the dsk2file code, because I wouldn't have put it online without at least a passing test... Anyway, I need to upload a fixed version...)

**Comment by fachat** [comment]
Additional note: the written file is seen as closed by the used drive - however, the disk image contains a splat file instead, which becomes visible after init/reset of the drive. We currently close the file regularly, not leaving a splat file. A fix for that (if at all) is left for later...

**Comment by fachat** [comment]
No test case yet. So keep open.

**Comment by greg-king5** [comment]
Another note:

Files must be closed normally; i.e., if a file was being written, then for that file:
1. the end of the file is "marked",
2. the last data is flushed to the disk,
3. the directory is updated,
4. and, the BAM is updated, and flushed to the disk!

Remember that a command-file closure is meant to clean up everything; it must not leave behind any unfinished business (no splat files, no missing or extra allocated blocks).

**Comment by fachat** [comment]
@greg-king5 indeed - but note that the CBM DOS does not close the files correctly when closing the command channel. Splat files remain (visible only after refreshing the disk blocks).

**Comment by greg-king5** [comment]
I think that those splat files are a VICE bug.  I never have seen them on real drives after the command channel is closed.  I think that VICE isn't flushing a disk image buffer properly.  Resetting the drive -- in VICE -- throws away the "dirty" buffer.

**Comment by fachat** [comment]
@greg-king5  thanks for insisting. I just can't seem to re-create the situation with the splash files in VICE. Maybe my user error. However, "dsk2file.prg" actually works on VICE if truedrive emulation is OFF, but fails - as expected, like the real drive - with truedrive emulation ON. I will open a bug with the VICE team.

**Comment by fachat** [comment]
For reference: https://sourceforge.net/p/vice-emu/bugs/697/
