### ISSUE TITLE
CBM DOS writes a bogus 0x0d into an empty file

### ISSUE THREAD

**Issue by fachat** [fachat/XD2031#155]
OPENing and creating a new file from BASIC, then immediately closing it writes a 0x0d into the file. So the file is not empty even though nothing has been written to it.

See fw testcases "files/f0" and "files/tprg1" for example.

**Comment by fachat** [comment]
Even though I REALLY don't like this, this may be one of the things some old programs may actually use. So we'll fix that. Somehow.

**Comment by greg-king5** [comment]
It's required because of the way that End-Of-File is signalled.  The EOF flag is attached to the last character that is sent.  Therefore, there always must be at least one character.  A carriage-return is used because it terminates BASIC's `INPUT#` statement.

**Comment by fachat** [comment]
Note: included in channel handling. When a WRITE ONLY channel is closed, and no data had been written, the firmware automatically sends a 0x0d before a close. This should make the behaviour consistent across all providers.
