### ISSUE TITLE
XS1541 write to file with single bytes is missing bytes

### ISSUE THREAD

**Issue by fachat** [fachat/XD2031#178]
With a PET 8032 and an XS1541 it seems that writing an 8k file using a BASIC loop (using single char() print#s) is loosing bytes.

**Comment by fachat** [comment]
It seems ATN commands get through ok, but sometimes bytes written by the PET are ignored:

```
>>>: BusAttention(28)
>>>: Bus: LISTEN/TALK (BusAttention(28)->TrapDevice=28, st=2800
>>>: BusAttention(61)
>>>: ***BusCommand 28 61
>>>: BusAttention(61)->TrapDevice=28, st=2800
INF:cmd - :4 bytes @0x5587e86ba19b : 
0000  09 04 01 FF                                       |                |
INF:WRITE_WITH_EOF(1)
0000  00                                                |                |
>>>: BusAttention(3f)
>>>: BusAttention(3f)->TrapDevice=00, st=0020
>>>: BusAttention(28)
>>>: Bus: LISTEN/TALK (BusAttention(28)->TrapDevice=28, st=2800
>>>: BusAttention(61)
>>>: ***BusCommand 28 61
>>>: BusAttention(61)->TrapDevice=28, st=2800
>>>: BusAttention(3f)
>>>: BusAttention(3f)->TrapDevice=00, st=0020
>>>: BusAttention(28)
>>>: Bus: LISTEN/TALK (BusAttention(28)->TrapDevice=28, st=2800
>>>: BusAttention(61)
```

**Comment by fachat** [comment]
@snhirsch can you pls check that (it's merged into branch 177)

**Comment by snhirsch** [comment]
I tried the new code and firmware.  Still not able to copy a large REL file from a real SFD1001 (8250 format) to a mounted D82 image in xdserver.  The source file is 4098 blocks, but after copy stops the target disk reports the file at 1158.  All read and write calls are checked for errors and I'm not seeing any.  Any possibility the 8250 emulation has problems?  Another thought: My code is not sending  'p' commands to position to next block.  I'm relying on the fact that all other drives I've tried advance automatically after read and/or write of records.  Is it possible xd2031 is losing its way?  Also, after getting record count and size from the source I create the target file and write a single byte to its last record to 'expand' it.  Is it wrong to assume that xd2031 is doing this properly?  Maybe I'm misunderstanding how far the drive-image based emulation goes.

Unfortunately, I don't know how to interpret that trace.  Also, my copy operation is not using single-byte writes.  My modified CBM Commander uses repeated block writes from a 254 byte buffer.

On a slightly related subject: Today I started experiencing PET IEEE timeouts while reading a 4000 block SEQ file from the host file system.  Turning off the timeout provides a workaround.

**Comment by fachat** [comment]
Bummer. 

The REL file emulation should behave very closely to the actual system (incl. e.g. expanding a file after creation, moving from one record to another etc), so this is really strange.

Couple of questions:
- did the IEEE timeouts while reading the SEQ appear just with the new version and disappear with the old version?
- looks like you have some simple test cases - couid you provide them (via PM)?

**Comment by snhirsch** [comment]
In the interim, I tried working with a D64 image.  Same issues, but now I see corrupted reads from the REL file in the image.  Among other bits of misbehavior, xd2031 seems to return the first record of the file twice in a row without advancing to the next.  Everything from that point on is a mixture of valid data and short runs of garbage.

All my testing is being done with my modified version of CBM Commander, which is not properly supported by the release version of VICE you use.  It's fine with the r38823 version here.  Nothing automated about the tests.  I just copy things around and analyze results by poking at files written to a mounted Linux directory.  For example: I start with a D64 image of SuperPET OS-9.  Under VICE I can copy out the 600+ block REL file 'os9 drive a'.  It's a valid copy.  Then, I mount the same D64 image as U10,D1 in xd2031 and try the same operation on the PET hardware. Result is corrupted.  I throw bits around between any combination of SFD1001, 4040, HardBox and Linux native directory served by xd2031.  No problems at all (besides IEEE timeouts on reads from xd - need to turn the timeout off).

**Comment by fachat** [comment]
If I had the test cases I could run them on my own 8032, and check myself

**Comment by snhirsch** [comment]
Are you ok with building that later version of VICE?  If so, I'll give you my latest working copy of CBM Commander and the disk images I'm working with.

**Comment by fachat** [comment]
There was a debounce-issue with (at least my) xs1541 setup. I added debounce, and optimized the ndac/nrfd handling somewhat.
